name: Go Android ARM64 Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-android-arm64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Download and install Android NDK r25b
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip -d ${{ runner.temp }}
        echo "NDK installed to: ${{ runner.temp }}/android-ndk-r25b"

    - name: Build for Android ARM64
      env:
        GOOS: android
        GOARCH: arm64
        CGO_ENABLED: 1
        CC: ${{ runner.temp }}/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
      run: |
        mkdir -p dist
        echo "Using CC: $CC"
        which $CC || (echo "Compiler not found!" && exit 1)
        go build -v -o dist/keyforward-android-arm64 ./...

    - name: Compress Output
      run: |
        cd dist
        tar -czf keyforward-android-arm64.tar.gz keyforward-android-arm64
        rm keyforward-android-arm64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-arm64-build
        path: dist/
